### ISSUE TITLE
Compile error when building CXX object CMakeFiles/sharklib.dir/src/hdf5/io/iobase.cpp.o

### ISSUE THREAD

**Issue by louiseseeyave** [ICRAR/shark#13]
Hello,

I tried compiling shark 2.0 with the follow modules (on an HPC):
1) gsl/2.5   2) cmake/3.25.1   3) gnu_comp/7.3.0   4) boost/1_64_0   5) hdf5/1.10.3

Here is the output I get after entering `cmake ..` in the `build` directory:
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /cosma/local/gcc/7.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /cosma/local/gcc/7.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found GSL: /cosma/local/gsl/2.5/include (found version "2.5") 
-- Found HDF5: /cosma/local/hdf5/gnu_7.3.0/1.10.3/lib/libhdf5.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found version "1.10.3") found components: C 
-- Using HDF5 version 1.10.3
-- HDF5 libraries / C++ libraries:  /cosma/local/hdf5/gnu_7.3.0/1.10.3/lib/libhdf5.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so / 
-- Found Boost: /cosma/local/boost/gnu_7.3.0/1_64_0/include (found suitable version "1.64.0", minimum required is "1.54") found components: filesystem log program_options system date_time log_setup thread regex chrono atomic 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done
-- Generating done
-- Build files have been written to: /cosma7/data/dp004/dc-seey1/modules/shark/build

And the error occurs at this stage after entering `make all`:
[ 79%] Building CXX object CMakeFiles/sharklib.dir/src/hdf5/io/iobase.cpp.o
/cosma7/data/dp004/dc-seey1/modules/shark/src/hdf5/io/iobase.cpp: In member function ‘void shark::hdf5::IOBase::close()’:
/cosma7/data/dp004/dc-seey1/modules/shark/src/hdf5/io/iobase.cpp:46:17: error: ‘class boost::optional<shark::hdf5::File>’ has no member named ‘has_value’; did you mean ‘value’?
  if (!hdf5_file.has_value()) {
                 ^~~~~~~~~
                 value
make[2]: *** [CMakeFiles/sharklib.dir/src/hdf5/io/iobase.cpp.o] Error 1
make[1]: *** [CMakeFiles/sharklib.dir/all] Error 2
make: *** [all] Error 2

Any advice? Thanks in advance!

**Comment by rtobar** [comment]
Thanks for reporting this! This seems to be a small incompatibility with the older version of boost you are using, which we didn't account for. In the meantime, if you try with a newer version of boost hopefully things should work.

**Comment by louiseseeyave** [comment]
Ah I see! A newer version of Boost worked for me - I used 1.82.0. Thanks for your help.

**Comment by rtobar** [comment]
I've bumped the minimum required version of Boost that better reflects the real dependency that shark requires (1.68 instead of 1.54).
